# Tugas 1 Eksplorasi Data

## Mengumpulkan data
Menarik data iris dari posgesql kemudian dibaca dengan python dijadikan dataframe

In [ ]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\acer\appdata\local\programs\python\python310\lib\site-packages (2.9.5)

WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the 'C:\Users\ACER\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [ ]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.5.3-cp310-cp310-win_amd64.whl (10.4 MB)
     -------------------------------------- 10.4/10.4 MB 394.8 kB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\acer\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
     ---------------------------------------- 14.8/14.8 MB 1.6 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\acer\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.24.2 pandas-1.5.3

WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the 'C:\Users\ACER\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [ ]:
import pandas as pd
import psycopg2 as ps

Koneksi Database

In [ ]:
conn2 = ps.connect(dbname ="postgres",
                   user = "postgres",
                   password = "130902",
                   host = "localhost",
                   port = "5432")

In [ ]:
import psycopg2
import pandas as pd
# Connection parameters, yours will be different
param_dic = {
    "host"      : "localhost",
    "database"  : "postgres",
    "user"      : "postgres",
    "password"  : "130902"
}
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

In [ ]:
def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

Menampilkan Dataframe Database

In [ ]:
# Connect to the database
conn = connect(param_dic)

column_names = ["sepal_length", "sepal_width", "petal_length", "petal_width","variety"]
# Execute the "SELECT *" query
df = postgresql_to_dataframe(conn, "select * from iris", column_names)
df.head()

Connecting to the PostgreSQL database...
Connection successful

  sepal_length sepal_width petal_length petal_width variety
0          5.1         3.5          1.4          .2  Setosa
1          4.9           3          1.4          .2  Setosa
2          4.7         3.2          1.3          .2  Setosa
3          4.6         3.1          1.5          .2  Setosa
4            5         3.6          1.4          .2  Setosa